apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
spec:
  secretName: app
  issuerRef:
    name: production-app
    kind: ClusterIssuer
  commonName: hustlerhimanshu.tech
  dnsNames:
  - hustlerhimanshu.tech
